site_name: SotaBench
theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  logo:
    icon: 'near_me'

nav:
    - Home: index.md
    - Benchmark Your Model: submit_model.md
    - Create a Benchmark: create_benchmark.md
    - Getting Started: getting_started.md
